#![deny(clippy::print_stdout, clippy::print_stderr)]
pub mod agents;
pub mod denial;
pub mod archive;
pub mod wrapper;
pub mod help_schema;
pub mod clean;
pub mod config;
pub mod context;
pub mod github;
pub mod credentials;
pub mod epic;
pub mod git_util;
pub use git_util as git;
pub mod worktree;
pub use ticket::ticket_fmt;
pub mod init;
pub mod logger;
pub mod start;
pub mod state;
pub mod sync;
pub mod sync_guidance;
pub mod review;
pub mod spec;
pub mod ticket;
pub mod work;
pub mod worker;
pub mod hash_stamp;
pub mod validate;
pub use state::{TransitionOption, compute_valid_transitions};
pub use ticket::{BlockingDep, compute_blocking_deps};
